CREATE TABLE addresses (
    id INT(11) NOT NULL AUTO_INCREMENT,
    post_code VARCHAR(7) NOT NULL,
    prefecture VARCHAR(10) NOT NULL,
    city VARCHAR(20) NOT NULL,
    street VARCHAR(40) NOT NULL,
    position GEOMETRY,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET = UTF8;